### ISSUE TITLE
Broken on 0.7

### ISSUE THREAD

**Issue by albop** [JuliaStats/StatsBase.jl#417] opened 2018-09-21 15:50 UTC
It is now impossible to install to install StatsBase on 0.7. I suspect an unwanted dependency has been introduced.

This is the message I get on a clean install:
```
ERROR: Unsatisfiable requirements detected for package Missings [e1d29d7a]:
 Missings [e1d29d7a] log:
 ├─possible versions are: [0.2.0-0.2.10, 0.3.0] or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with StatsBase [2913bbd2] to versions: [0.2.0-0.2.10, 0.3.0] — no versions left
   └─StatsBase [2913bbd2] log:
     ├─possible versions are: [0.1.0, 0.2.0-0.2.1, 0.2.3-0.2.10, 0.3.0-0.3.13, 0.4.0-0.4.4, 0.5.0-0.5.3, 0.6.0-0.6.16, 0.7.0-0.7.4, 0.8.0-0.8.3, 0.9.0, 0.10.0, 0.11.0-0.11.1, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0, 0.16.0-0.16.1, 0.17.0, 0.18.0, 0.19.0-0.19.5, 0.20.0-0.20.1, 0.22.0, 0.23.0-0.23.1, 0.24.0, 0.25.0] or uninstalled
     ├─restricted to versions * by an explicit requirement, leaving only versions [0.1.0, 0.2.0-0.2.1, 0.2.3-0.2.10, 0.3.0-0.3.13, 0.4.0-0.4.4, 0.5.0-0.5.3, 0.6.0-0.6.16, 0.7.0-0.7.4, 0.8.0-0.8.3, 0.9.0, 0.10.0, 0.11.0-0.11.1, 0.12.0, 0.13.0-0.13.1, 0.14.0-0.14.1, 0.15.0, 0.16.0-0.16.1, 0.17.0, 0.18.0, 0.19.0-0.19.5, 0.20.0-0.20.1, 0.22.0, 0.23.0-0.23.1, 0.24.0, 0.25.0]
     └─restricted by julia compatibility requirements to versions: [0.24.0, 0.25.0] or uninstalled, leaving only versions: [0.24.0, 0.25.0]
```

**Comment by ararslan** [comment] 2018-09-21 16:45
Perhaps related to https://github.com/JuliaData/Missings.jl/issues/90?

**Comment by nalimilan** [comment] 2018-09-21 16:46
Yeah, that's probably due to the fact that we claim to support 0.7 prereleases, which are older than 0.7.0 so we got capped. Tagging a new release should do the trick: https://github.com/JuliaLang/METADATA.jl/pull/18217

**Comment by nalimilan** [comment] 2018-09-21 16:49
Maybe merge https://github.com/JuliaStats/StatsBase.jl/pull/418 and re-tag? I'm not sure what's the rule for capping.

**Comment by ararslan** [comment] 2018-09-21 17:33
Closing since the issue is with a different package.

**Closed by ararslan** 2018-09-21 17:33 UTC

**Comment by simonbyrne** [comment] 2018-09-21 18:57
Do we still need Missings as a dependency?

**Comment by ararslan** [comment] 2018-09-21 19:00
We're using it here:
https://github.com/JuliaStats/StatsBase.jl/blob/88b481809cf3a4b4e381be37f4372122c2d7c361/src/ranking.jl#L186
