### ISSUE TITLE
Method ambiguities reported by Aqua

### ISSUE THREAD

**Issue by prbzrg** [JuliaStats/StatsBase.jl#909] opened 2023-12-27 17:58 UTC
In Julia v1.10, I used Aqua to detect method ambiguities in my package https://github.com/impICNF/ContinuousNormalizingFlows.jl/issues/356 and some of its report were related to this package:

```julia
Ambiguity #10
==(x::Union{StatsBase.PValue, StatsBase.TestStat}, y::Real) @ StatsBase ~/.julia/packages/StatsBase/WLz8A/src/statmodels.jl:90
==(x::Real, y::AbstractIrrational) @ Base irrationals.jl:90

Possible fix, define
  ==(::Union{StatsBase.PValue, StatsBase.TestStat}, ::AbstractIrrational)

Ambiguity #11
==(y::Real, x::Union{StatsBase.PValue, StatsBase.TestStat}) @ StatsBase ~/.julia/packages/StatsBase/WLz8A/src/statmodels.jl:91
==(x::AbstractIrrational, y::Real) @ Base irrationals.jl:89

Possible fix, define
  ==(::AbstractIrrational, ::Union{StatsBase.PValue, StatsBase.TestStat})

Ambiguity #33
StatsBase.TestStat(v) @ StatsBase ~/.julia/packages/StatsBase/WLz8A/src/statmodels.jl:80
(::Type{T})(x::Base.TwicePrecision) where T<:Number @ Base twiceprecision.jl:265

Possible fix, define
  StatsBase.TestStat(::Base.TwicePrecision)

Ambiguity #34
StatsBase.TestStat(v) @ StatsBase ~/.julia/packages/StatsBase/WLz8A/src/statmodels.jl:80
(::Type{T})(z::Complex) where T<:Real @ Base complex.jl:44

Possible fix, define
  StatsBase.TestStat(::Complex)

Ambiguity #35
StatsBase.TestStat(v) @ StatsBase ~/.julia/packages/StatsBase/WLz8A/src/statmodels.jl:80
(::Type{T})(x::AbstractChar) where T<:Union{AbstractChar, Number} @ Base char.jl:50

Possible fix, define
  StatsBase.TestStat(::AbstractChar)


```

I would appreciate your attention to this issue.

**Comment by devmotion** [comment] 2024-01-03 15:38
Duplicate of #861. Fixed by #866.

**Closed by devmotion** 2024-01-03 15:38 UTC
