### ISSUE TITLE
IQR does not work with DataFrame, is it intentional?

### ISSUE THREAD

**Issue by kirtsar** [JuliaStats/StatsBase.jl#461] opened 2019-02-07 12:17 UTC
Minimal example

```
using RDatasets
trees = dataset("datasets", "trees")
colwise(trees, iqr)
```

The error is:
`MethodError: no method matching iqr(::Array{Union{Missing, Int64},1})`

For some reasons iqr works only with subtypes of Array{Real}, no missings allowed.

But quantile works perfectly well with any type of arrays.

**Comment by ararslan** [comment] 2019-02-07 17:18
Seems like an oversight.

**Comment by nalimilan** [comment] 2019-02-08 12:55
That's actually unrelated to data frames. Duplicate of https://github.com/JuliaStats/StatsBase.jl/issues/449. Help welcome to fix methods on by one to accept more general argument types.

**Closed by nalimilan** 2019-02-08 12:55 UTC
